### ISSUE TITLE
Background images not showing

### ISSUE THREAD

**Issue by macsupport** [janwagner/respio#1]
Seems the background images are not showing (in Chrome, Safari or Firefox)

**Comment by janwagner** [comment]
Have you tried the [demo page](http://dev.janwagner-design.de/respio/demo_responsive_background_image.html), or the demo code?
I've tested the demo page in all your mentioned browsers and it is working.

**Comment by macsupport** [comment]
Sorry I wasn't clear. When I download the Repo and run _demo_responsive_background_image.html_, no background images show. I haven't uploaded to a server yet to see if it is a local issue. Not getting any console errors.

**Comment by janwagner** [comment]
Thank you for reporting this issue. I have updated the files. Should be working now :)

**Comment by macsupport** [comment]
The background  images now show but it seems they are not responsive.

**Comment by janwagner** [comment]
If you want to have responsive "background" images, you'll have to make the container responsive.
What my script does is to set a pixel perfect image as background image of your <div> on load.

For example, if your origin image is 3000x1500 and your div is 500x250, than the background image will also be 500x250. The user will never load the larger image, only the pixels he needs.
